/// Flutter icons WarmdIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WarmdIcons
///      fonts:
///       - asset: fonts/WarmdIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WarmdIcons {
  WarmdIcons._();

  static const _kFontFam = 'WarmdIcons';

  static const IconData cash_multiple = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData coin_outline = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData radiator = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData account_group = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData fuel = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData wind_turbine = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData car_sports = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData gas_station = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData sprout = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData piggy_bank = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData cow = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData food_apple_outline = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData food_off = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData food = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData cheese = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData human_male = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData human_male_girl = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData tshirt_crew_outline = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData earth = const IconData(0xe81a, fontFamily: _kFontFam);
}
